### ISSUE TITLE
Obsolete version in PMO struct.

### ISSUE THREAD

**Issue by mixakamenev** [dsuch/pymqi#104]
\_\_init\_\_.py +473 at 41c27c3899d942a89b8e2fb40459863319dd745b

```python
class PMO(MQOpts):
    """PMO(**kw)

    Construct a MQPMO Structure with default values as per MQI. The
    default values may be overridden by the optional keyword arguments
    'kw'."""

    def __init__(self, **kw):
        opts = [
            ['StrucId', CMQC.MQPMO_STRUC_ID, '4s'],
            ['Version', CMQC.MQPMO_VERSION_1, MQLONG_TYPE],
            ['Options', CMQC.MQPMO_NONE, MQLONG_TYPE],
            ['Timeout', -1, MQLONG_TYPE],
            ['Context', 0, MQLONG_TYPE],
            ['KnownDestCount', 0, MQLONG_TYPE],
            ['UnknownDestCount', 0, MQLONG_TYPE],
            ['InvalidDestCount', 0, MQLONG_TYPE],
            ['ResolvedQName', b'', '48s'],
            ['ResolvedQMgrName', b'', '48s'],
            ['RecsPresent', 0, MQLONG_TYPE],
            ['PutMsgRecFields',  0, MQLONG_TYPE],
            ['PutMsgRecOffset', 0, MQLONG_TYPE],
            ['ResponseRecOffset', 0, MQLONG_TYPE],
            ['PutMsgRecPtr', 0, 'P'],
            ['ResponseRecPtr', 0, 'P']]

        if "7.0" in pymqe.__mqlevels__:
            opts += [
                ['OriginalMsgHandle', py23long(0), 'q'],
                ['NewMsgHandle', py23long(0), 'q'],
                ['Action', py23long(0), MQLONG_TYPE],
                ['PubLevel', py23long(0), MQLONG_TYPE]]

        super(PMO, self).__init__(tuple(opts), **kw)
```
`'Version'` is `CMQC.MQPMO_VERSION_1`.
According to the documentation https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_9.0.0/com.ibm.mq.ref.dev.doc/q098650_.htm :
> Note
The remaining fields are ignored if Version is less than MQPMO_VERSION_2.
RecsPresent
PutMsgRecFields
PutMsgRecOffset
ResponseRecOffset
PutMsgRecPtr
ResponseRecPtr

> Note
The remaining fields are ignored if Version is less than MQPMO_VERSION_3.
OriginalMsgHandle
NewMsgHandle
Action
PubLevel

Without this patch using all fields of PMO struct is impossible:
```diff
diff --git a/code/pymqi/__init__.py b/code/pymqi/__init__.py
index d7c8bc8..34996bf 100644
--- a/code/pymqi/__init__.py
+++ b/code/pymqi/__init__.py
@@ -468,9 +468,13 @@ class PMO(MQOpts):
     'kw'."""
 
     def __init__(self, **kw):
+        _mqpmo_version = CMQC.MQPMO_VERSION_2
+        if "7.0" in pymqe.__mqlevels__:
+            _mqpmo_version = CMQC.MQPMO_VERSION_3
+
         opts = [
             ['StrucId', CMQC.MQPMO_STRUC_ID, '4s'],
-            ['Version', CMQC.MQPMO_VERSION_1, MQLONG_TYPE],
+            ['Version', _mqpmo_version, MQLONG_TYPE],
             ['Options', CMQC.MQPMO_NONE, MQLONG_TYPE],
             ['Timeout', -1, MQLONG_TYPE],
             ['Context', 0, MQLONG_TYPE],
```

**Comment by SeyfSV** [comment]
I think it is better to use MQPMO_CURRENT_VERSION and MQGMO_CURRENT_VERSION.
I use this [patch](https://github.com/SeyfSV/pymqi/commit/007dfea43cf232056a315d634e7eb43c0f253baf).
Yes it is not full and cover only specific version.

**Comment by mixakamenev** [comment]
Yes, using CMQC.MQPMO_CURRENT_VERSION is a better solution.

**Comment by SeyfSV** [comment]
@mixakamenev , it was our mistake and this is not issue.
By default MQ create headers with all available (for local MQ installation version) fields , but use only that compatible with provided in `Version` field version/value (_The remaining fields are **ignored** if Version is less than MQPMO_VERSION_2._).
Right way is:
`pmo=pymqi.PMO('Version'=pymqi.CMQC.MQPMO_CURRENT_VERSION )`

**Comment by mixakamenev** [comment]
@SeyfSV , Yes ```python pmo=pymqi.PMO('Version'=pymqi.CMQC.MQPMO_CURRENT_VERSION )``` works. Having to explicitly pass an argument defined in the library looks a bit strange. However this is a way.

**Comment by dsuch** [comment]
> Having to explicitly pass an argument defined in the library looks a bit strange. However this is a way.

Hi @mixakamenev,

I have not followed this thread closely - can you please tell me what you would suggest be changed for things to be less surprising from your perspective?

Thanks.

**Comment by mixakamenev** [comment]
> can you please tell me what you would suggest be changed for things to be less surprising from your perspective?

Hi, @dsuch,

so
```diff
diff --git a/code/pymqi/__init__.py b/code/pymqi/__init__.py
index 79efdfa..910c1f9 100644
--- a/code/pymqi/__init__.py
+++ b/code/pymqi/__init__.py
@@ -470,7 +470,7 @@ class PMO(MQOpts):
     def __init__(self, **kw):
         opts = [
             ['StrucId', CMQC.MQPMO_STRUC_ID, '4s'],
-            ['Version', CMQC.MQPMO_VERSION_1, MQLONG_TYPE],
+            ['Version', CMQC.MQPMO_CURRENT_VERSION, MQLONG_TYPE],
             ['Options', CMQC.MQPMO_NONE, MQLONG_TYPE],
             ['Timeout', -1, MQLONG_TYPE],
             ['Context', 0, MQLONG_TYPE],
```
or
```diff
diff --git a/code/pymqi/__init__.py b/code/pymqi/__init__.py
index 79efdfa..82a5aa0 100644
--- a/code/pymqi/__init__.py
+++ b/code/pymqi/__init__.py
@@ -470,7 +470,7 @@ class PMO(MQOpts):
     def __init__(self, **kw):
         opts = [
             ['StrucId', CMQC.MQPMO_STRUC_ID, '4s'],
-            ['Version', CMQC.MQPMO_VERSION_1, MQLONG_TYPE],
+            ['Version', CMQC.MQPMO_VERSION_2 if "7.0" in pymqe.__mqlevels__ else CMQC.MQPMO_VERSION_3, MQLONG_TYPE],
             ['Options', CMQC.MQPMO_NONE, MQLONG_TYPE],
             ['Timeout', -1, MQLONG_TYPE],
             ['Context', 0, MQLONG_TYPE],
```
if PMO fields construction depends on ```python pymqe.__mqlevels__```

Minimal set of PMO fields matches CMQC.MQPMO_VERSION_2.
https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_9.0.0/com.ibm.mq.ref.dev.doc/q098650_.htm

**Comment by dsuch** [comment]
Right, thus, the idea is to include newer fields in the structure / assume that MQ versions will be rather new instead of assuming that MQ versions will be old, is that correct?

**Comment by mixakamenev** [comment]
If the idea is to assume compatibility with older versions, then my patch will not work.
I didn't think about it well enough. Issue needs to be closed.

**Comment by dsuch** [comment]
That is the idea but I am also thinking aloud myself - how many MQ systems will support only PMO v1.

We can expect for MQ environments to be conservative but catering to systems that cannot support PMO v2 means pre-MQ 7.0 installations, which must be at least 10-15 years old now.

Hence, I think your idea is good - we can support the newer ones by default and programs connecting to the older ones will always be able to specify an older version of PMO.

Just so you know, I tend to work on PyMQI once in a while, collecting all the patches and ideas in one go so please do not be surprised if your code is not committed immediately - same goes for @SeyfSV's patches. Thanks.

**Comment by mixakamenev** [comment]
I completely agree with your thoughts about the old MQ systems. If users of older MQ versions decide to update the pymqi library, they will need to explicitly pass old version of PMO.

No need for immediate changes.
Thanks for your work.

**Comment by SeyfSV** [comment]
It's ok, when you use local MQ with one installation, but usually we connect to remote MQ systems, where version can be less than version of local MQ client. In this case, i think, we get MQRC_PMO_ERROR.
Current way is better, because by default you use version that supported by all MQ versions. When you want to use some feature from older version you explicitly set version in header.

**Comment by dsuch** [comment]
Hi @SeyfSV - do you tend to connect to MQ versions less than 7.0?

**Comment by SeyfSV** [comment]
No :), only 8+
But this breaks IBM logic.
For [example](https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_9.1.0/com.ibm.mq.ref.dev.doc/q098660_.htm)
> The header, COPY, and INCLUDE files provided for the supported programming languages contain the most-recent version of MQPMO that is supported by the environment, but with the initial value of the Version field set to MQPMO_VERSION_1. To use fields that are not present in the version-1 structure, the application must set the Version field to the version number of the version required.

**Comment by dsuch** [comment]
Question is if this recommendation was not written 10 years ago when MQPMO_VERSION_2 first appeared and if it still makes sense today to cling to it.

But, at any rate, we can keep the logic that we have for now until it turns out it is too problematic - I recall a ticket some time ago where someone could not use GroupId in get or put, I do not recall, but it was about the same thing, that this attribute was not available in VERSION_1 of the respective structure.

Since I have your attention @SeyfSV - can you please point me to PRs / patches that you would like me to merge? I will make a side note to include them in the next release. Thanks.

**Comment by SeyfSV** [comment]
Really this question is not  about PMO structure only, it concerns all MQ headers and structures. All of it use <obj>_VERSION_1, and if you decide to change Version in PMO you should change Version for all.
At this moment I sink that current pymqi state is right and does not require any changes, because pymqi is just a proxy for MQ library and it should not change programming way.

**Comment by dsuch** [comment]
Yes, naturally, this is an exchange of thoughts about headers other than PMO too. 

As for PyMQI - I like the fact that it is low-level because it does not impose any particular programming model to its users but on the other hand, IBM docs are written by humans too.

My take in this particular case is that this comment was written many years ago and simply does apply to any environment anymore because a pre-7.0 one is a rare bird now so I see no problems with making life easier for people if 99% of users will be on at least 8.0 now.

At any rate, let us keep things as they are for now and we shall see what to do in the future. If there are more tickets like this one, this will probably warrant a change to the defaults used.

**Comment by SeyfSV** [comment]
Yes, it make sense.
Thanks.
