### ISSUE TITLE
Converting to bytes format for message, changes Asian characters.

### ISSUE THREAD

**Issue by gowdhammurthi** [dsuch/pymqi#138]
When I want to put a message in MQ. Pymqi requires the input to be in bytes format(not in python3 style string). This is not an issue when the input is in English. For instance, "abcd" is equivalent to b'abcd'. But when the input is in Asian characters like "你好", the bytes format changes it to b'\xe4\xbd\xa0\xe5\xa5\xbd'. How can we put a message as such ("你好").

Thanks

**Comment by dsuch** [comment]
There is no difference if you send bytes that represent English or non-English text, or of it represents any text at all.

You just send bytes and that is all that PyMQI requires and whether it is a human-readable language or, say, a JPEG file, there is no difference.

Note, however, that there are also options on MQ side as regards conversions and encodings but I am not really familiar with them, I am just replying to confirm that PyMQI simply needs bytes.

**Comment by chughts** [comment]
If both sending and receiving ends are expecting the same encoding then you don't need to do anything. If they are different then you might need to send the message as a string by setting the Format on the md (message descriptor) object. That will allow MQ to treat the data as a string and perform any required transformations. 

````
md.Format = pymqi.CMQC.MQFMT_STRING
````

**Comment by jjjw420** [comment]
This is a very common MQ problem and mostly an understanding problem when it comes to codepages(which is why I could not help myself gfrom commenting).    

I dont know how many times I've been asked to look at "funny characters" or "corrupt" messages in my time working with MQ.  From my experience - I can tell you that it's not funny and probably not corrupt -  it's just the way it's viewed, or MQ is doing what it's told to do.  

Code page handling and conversion can happen in more than on place in a MQ app.   So here's my two cents:

1.)    Ensure you set the MQMD.CCSID according to what the data you are sending really is.   If you leave it default(eg. zero) - it will use the default CCSID of the queue manager.  On most systems - that will probably be ASCII (eg cp437, cp819, cp1252, etc. etc.) which may not be suitable for your unicode(potentially muti-byte) data.

2.)   Setting MQFMT_STRING implies your message is safe for conversion.   That means that if your channel has conversion set or you set the MQGET option MQGMO_CONVERT, MQ will convert the message based on what's in MQMD.CCSID (or MQRFH2.CCSID if using JMS).   That means it may convert the code page of your message into something that it's not.

3.)  Check any other places you may convert binary to string/string to binary.   Who and what does the MQ Get?  If codepage conversion is involved in your code or by the application that does the MQGET -  you must make sure you tell what ever is doing that conversion to use the correct code page.   

**Now.... How do you solve this type of problem?**  
**_- Instead of looking at the messages in your text editor - use a hexidecimal editor._**   This is key.  You may think the data has changed due the way it is displayed - but in the end the character vaue in the message is important - not what it displayed.
- Check the hex value of your character you think is changing before and after your MQ operation.
- If the hexidecimal value is the same before and after - the data is the same and perhaps your text editor is not displaying what is really there.
- if it's different - check CCSID's (MQMD or JMS headers), check possible conversion by MQ.   
- if the messages are correct and identical but somewhere after MQ it is changing  - then try and see where.

If you still believe there to be an issue with conversion by pymqi - then much more information is required from you in order for it to be investigated seriosly - which is at least:
- what platform do you run on
- what platform is your queue manager on
- Before and after messages with all MQ headers present(eg. MQMD and RFH/RFH2 if using JMS or anything else related to rules and formatting headers) illustrating what has changed.
- MQPUT operation used and all PUT options used to PUT the message, 
- all MQGET operation options used to GET the message
- Simple sample to reproduce the issue.

Good luck!

**Comment by gowdhammurthi** [comment]
@chughts @jjjw420 , Hi , Thank you so much for all your help.
Setting CCSID (CodedCharSetId) as 1208,
Setting Format as MQSTR,
finally fixed it. 
This is has been a good research. I learnt a lot on MQ objects and encoding basics.
Thank you
