### ISSUE TITLE
Add info about setting up LD_LIBRARY_PATH(DYLD_LIBRARY_PATH) to documentation

### ISSUE THREAD

**Issue by SeyfSV** [dsuch/pymqi#157]
We have too many questions/issues (#15, #16, #65, #73, #89, #121, #131, #154 ) about adding MQ library path to $LD_LIBRARY_PATH / $DYLD_LIBRARY_PATH. I think it should be some info in documentation or readme about it.
There are great explanations from @JoshMcMQ and others:
https://github.com/dsuch/pymqi/issues/15#issuecomment-580557856
https://github.com/dsuch/pymqi/issues/65#issuecomment-396500388
https://github.com/dsuch/pymqi/issues/73#issuecomment-417847259
https://github.com/dsuch/pymqi/issues/89#issuecomment-462452447

My English is not good enough for writing documents, but it would be great if someone will summarize this info and add it to documentation

**Comment by dsuch** [comment]
Yes, I was pondering the same idea today - if only to be able to quickly link people to what they need.

It would be also nice to research the concept of ticket templates in GitHub.

Something along the lines of "Is your question about not being able to import pymqi?  Do you receive the libmqic_r.so: cannot open shared object file: No such file or directory message? If so, check here first" which leads the person to the relevant part of the documentation.

I like the comments from https://github.com/dsuch/pymqi/issues/15#issuecomment-580557856 - I can add it for Linux but someone else would have to do it for Mac and Windows.

Afterwards, I can coalesce everything and update the documentation.

**Comment by JoshMcMQ** [comment]
@dsuch the following is merged from a few of the comments and should cover Linux.   @chughts may be able to help with wording for Mac.  I think for windows you jujitsu need to put the redistributable bin directory into the PATH, setmqenv is also available. 
---
If you have installed a full MQ client install make sure you do one of the following:

1. Set the install as the primary install. To set a primary installation you can run the following command as root:

    `/opt/mqm/bin/setmqinst -p /opt/mqm -i`
2. Run the `setmqenv` command under the `bin` directory under MQ install location so that variables like `LD_LIBRARY_PATH` are correctly set to point to the MQ libraries for the MQ install.

If you are using 64 python you can run the following command, note the "dot space" at the start of the command to source the profile.  This sets the LD_LIBRARY_PATH along with other MQ specific ENV variables.

    `. /opt/mqm/bin/setmqenv -s -x 64 -l`
3. Manually export `LD_LIBRARY_PATH` to point to the `lib` (32bit) or `lib64` (64bit) directory under the MQ install location. 

If you have extracted the redistributable client then do one of the following:
1. Run the `setmqenv` command under the `bin` directory where you extracted the files so that variables like `LD_LIBRARY_PATH` are correctly set to point to the MQ libraries extracted there. 
2. Manually export `LD_LIBRARY_PATH` to point to the lib (32bit) or lib64 (64bit) directory under the directory where you extracted the files.

**Comment by AlexandreYang** [comment]
About MacOS we should also add this caveat MacOS "Runtime Protections" purging `DYLD_LIBRARY_PATH`: https://github.com/dsuch/pymqi/issues/200#issuecomment-645909117 and

**Comment by dsuch** [comment]
Mass-closing old tickets.
