### ISSUE TITLE
Removing double-underscore attributes

### ISSUE THREAD

**Issue by dsuch** [dsuch/pymqi#167]
Hello,

this is an advance warning that at one point I will remove double-underscore attributes from PyMQI objects.

For instance, this ..

```python
self.__handle = rv[0]
self.__name = name
```
.. will change to that:

```python
self.handle = rv[0]
self.name = name
```

They were added by someone else years ago and they stuck but they do hinder the development now and I will replace them with proper attributes.

Theoretically, they are private API attributes so they can be changed at any time but the reality is that people use them so I would like for this to be a notice placed well in advance in the hope that anyone who uses such attributes will read it.

**Comment by Skyler-Altol** [comment]
@dsuch for private API attributes that you still want people to access, it's recommended that a single _ be used. eg

`self._handle = rv[0]`

Reason being, single underscore attributes / methods are still accessible at runtime without any shenanigans, but they emphasise the fact that these vars are a private API (at least, by convention) and are subject to change.

```
Python 3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> class temp:
...     def __init__(self, dummy):
...         self._dummy = dummy
...
>>> var = temp("hello")
>>> print(var._dummy)
hello
>>>
```

**Comment by dsuch** [comment]
@Skyler-Altol Thanks. I understand how it works, you do not need to explain it, this is why I opened this ticket in the first place. 

Please understand that I am not the original author of PyMQI. It was conceived around 1999, I believe, and I took it over in 2004 I think. Since then, we have been living with various design decisions made by someone else.

The reason why double-underscore attributes have never been removed is that I am very big on backward compatibility - I still regularly get questions about MQ 5.3, Windows Server 2012 or RHEL 5 - and there are definitely applications that rely on this dubious choice of double underscores.

But at one point they will be removed, hence this ticket, to give an advance warning.

**Comment by Skyler-Altol** [comment]
That makes sense, though if people are raising questions about those platforms it's going to get interesting when we drop 2.7 because I'll guarantee a lot of the same apps that are using those ancient versions, will also be built against 2.7. So to simplify this, what do you think of a "clean break" whereby the lib drops 27, and the internals get rebuilt at the same time (factoring in the new design decisions). Given that's a major change, I would recommend incrementing to pymqi's version to 2.0 once that process kicks off.

I think it may be wise to create a thread discussing the future way forward for PyMQI's architecture. We're at a point where we have a really good opportunity to blow away the history that has held back this package for so many years, and I'd love to get input from everyone to see what they think the future of the package should be too. Perhaps features that should be supported, etc. Building around future scalability would also be useful given that IBM is cranking out feature updates like no tomorrow these days.

**Comment by dsuch** [comment]
Mass-closing old tickets.
