### ISSUE TITLE
AttributeError: module 'pymqi.CMQCFC' has no attribute 'MQCACF_CF_SMDS'

### ISSUE THREAD

**Issue by atulk0** [dsuch/pymqi#214]
I got AttributeError: module 'pymqi.CMQCFC' has no attribute 'MQCACF_CF_SMDS' error while trying to inquire the SMDS on Z/OS. The fix is to include the constants to CMQCFC.

**Comment by atulk0** [comment]
I was able to fix the issue by adding the constants to pymqi.CMQCFC

**Comment by dsuch** [comment]
Hello @atulk0,

this software is open-source. One of the tenets of open-source is sharing with others.

People work on PyMQI and share their results with others, including you, and the idea is that if you spot something like you did then you share it back because in this manner we are all stronger together.

With that in view, I ask you to create a pull request with the code that you see should be included in PyMQI. In this way, you will contribute to the project and make yourself part of the effort.

Otherwise, the impression that you leave is of a self-centred person who does not appreciate our work and opens a ticket only to close it in a moment because that particular person's needs have been already satisfied and we are no longer needed in that person's world.

Thank you.

**Comment by atulk0** [comment]
@dsuch I have created a pull request, it is waiting for review/approval.

**Comment by dsuch** [comment]
This is merged - thank you again!
