### ISSUE TITLE
please enhance the library to support remote command execution 

### ISSUE THREAD

**Issue by shivanekanti** [dsuch/pymqi#232]
We have quite a few queue managers configured for the remote command execution via a bridge/gateway queue manager. 
unfortunately the current version does not have the option of specifying the remote queue manager name while trying to open the command input queue. 
It would be of good help, if this enhancement could be implemented.

**Comment by dsuch** [comment]
Hello @shivanekanti - in terms of the C MQ API, what calls or options are missing? Thanks.

**Comment by shivanekanti** [comment]
Thanks for the quick response. 

This is what I did, I modified the __init__ as bellow 
....................................................................
in the PCFExecute class 
1) in the constructor __init__: 
1a) added
      remote_qm_name=b'',
next to 
    command_queue_name=b'SYSTEM.ADMIN.COMMAND.QUEUE

1b) added
   self.__remote_qm_name=remote_qm_name
next to 
  self.__command_queue_name=command_queue_name

2) added 
  @property
  def remote_qm_name(self):
  return self.__remote_qm_name
before this line
  @property
  def command_queue_name(self):

3) then changed the code that is opening the command queue to bellow 
Current Code is 
command_queue=Queue(self.__pcf.qm,self.__pcf.command_queue_name,CMQC.MQOO_OUTPUT) 

I changed it to: 
admin=OD()
admin.ObjectName=self.__pcf.command_queue_name
admin.ObjectQMgrName=self.__pcf.remote_qm_name
command_queue=Queue(self.__pcf.qm,admin,CMQC.MQOO_OUTPUT) 


Now with the above changes. My code can connect to gateway queue manager and issue:
PCFExecute( ... remote_qm_name=b'REMOTEQMGR') 

now the messages will be put directly to the XMIT Queue named after the REMOTEQMGR from there the sdr/rcvr channel pairs carry the commands to the queue manager and gets the responses back to the dynamic queues on the gateway queue manager. 

I made the above changes and did a quick test between two Linux queue managers. 
I am yet to test with Linux queue manager being gateway and ZOS queue manager being the remote queue manager. 

once again. 
thanks for the help.

**Comment by dsuch** [comment]
You know, instead of copy-pasting code here, it would be best if you forked this repository to your own under GitHub handle and sent a link here to share the code.

**Comment by shivanekanti** [comment]
what you are saying is what I would like to do In future for sure. But at the moment, unfortunately I need clearance/approval in our organization to be able to contribute to open source projects.  It will take some more time for that to be complete, hence this request. 
Apart from that, I am very newbie to python coding, so not confident enough :)
thanks for help.

**Comment by dsuch** [comment]
Do not worry about Python coding, if the idea is good then someone will pick it up and rewrite code if needed.

You also need to put yourself in our shoes. What you are saying is that your organisation is happy to make use of fruits of someone else's labour but, because it is so inflexible that sending a simple code patch requires a lot of red tape, it would be great if this feature was implemented without your having to wait.

I am sorry but if you meant that someone should do it for free then this is not a strongly convincing argument.

**Comment by dsuch** [comment]
Just to confirm it - I understand your situation, that you are likely caught in the middle and would just like to go ahead with your work.

What I am saying is that an argument about an apparently large organisation that uses open-source software, without contributing anything back, whose employee would like for other people to continue to work to for free, in order to work around the organisation's inflexibility, simply does not sound good.

Thus, if you send a link to the code in your own fork I will be happy to look it over but otherwise, I will not work on it, particularly because I have no need for this functionality. Of course other people here are free to implement it if they choose so. Thanks.

**Comment by shivanekanti** [comment]
I think, I gave totally wrong impression. Sorry  for miscommunication 

As an organization we do contribute to open source projects. I know quite a few teams that regularly contribute to open source projects. 

It is just that, we are at the beginning stage with the  pymqi for our new POC/project it will be sometime before we get all the approvals in place, after that it will not be an issue to contribute. Approval is more at a component/product level not specific for each change/contribution. 

In simple words, I will be able to make the changes after few days from now. I will update this thread after make the changes.

Thanks for help.

**Comment by dsuch** [comment]
Ah, I see, that sounds better indeed. I just thought it was yet another major company using PyMQI and expecting improvements to happen just like that. Thanks for correcting me.

**Comment by shivanekanti** [comment]
We no longer need this enhancement. Instead of code changes to pymqi, we are able to accomplish the same result by defining QREMOTE object pointing to the COMMAND QUEUE on the remote Queue Manager.

**Comment by SeyfSV** [comment]
@shivanekanti , that is good request for enhancement. It should be kept open untill someone takes the time to improve pymqi.

**Comment by dsuch** [comment]
Mass-closing old tickets.
