### ISSUE TITLE
.jks key in SSL connection

### ISSUE THREAD

**Issue by MrEzio** [dsuch/pymqi#248]
Hi!
Just like the title says it, I have a `.jks` key and I would like to use it to connect with pymqi. I already did the conversion to a `.kdb` key and stashing the password in a `.sth` and it works with that method, but I really need it to work with only a `.jks` if possible. I have functions that can have the infos of the key, I just don't know how to use them in pymqi.

Thank you for your help!

**Comment by JoshMcMQ** [comment]
It is but possible.   pymqi uses the MQI C API libraries which work with the CMS key store for (`kdb/sth`).  The MQI C API does not work with Java Key Stores (`jks`).

**Comment by JoshMcMQ** [comment]
You already asked the same question in issue https://github.com/dsuch/pymqi/issues/247, the answer is not any different now than it was then.

I don't think it work make much sense for a non Java program to sort a Java specific key store format.   But in any case this is not a pymqi issue.  If you want to request IBM to enhance the product so that non-Java APIs support jks file the you could submit a request for enhancement at the link below:

[IBM MQ RFE Community](https://www.ibm.com/developerworks/rfe/execute?use_case=changeRequestLanding&PROD_ID=520)

**Comment by MrEzio** [comment]
I see. Thanks a lot again for the explanation and infos @JoshMcMQ !
