### ISSUE TITLE
Weblogic

### ISSUE THREAD

**Issue by drychlik76** [dsuch/pymqi#46]
Hello,

I am attempting to create a python script to connect to a queue on a web logic server.  I keep getting Reason 2058: FAILED: MQRC_Q_MGR_NAME_ERROR.  After numerous hours, I realized that it's really my ignorance of Websphere versus Weblogic.  The host provider gave me all the credentials that I need excluding the queue manager name.  My question is this.  How would I setup a queue manager without using web sphere installation to connect to this remote queue?  I am "assuming" that once that piece is setup correctly, I can then start reading messages from the queue using pymqi.  

I apologize that this is not a pymqi specific question, however I am grasping for any information or resource I can to get this project done.  Any help or direction would be greatly appreciated.  

Thank you in advance.

**Comment by dsuch** [comment]
Alright, but I'm still not 100% sure if you are to connect to a WebSphere MQ-based queue manager or not?

The message began with a notion of trying to connect to WebLogic-based queues and then you are asking how to set up a queue manager without a WebSphere MQ installation, so I'm just not sure what the intermediate goal is.

* I understand that ultimately the idea is that there are queues in a WebLogic server that you need to connect to
* PyMQI will not be able to connect to such queues - it works with WebSphere MQ
* If you are thinking of setting up a kind of a middle layer where PyMQI connects to WebSphere MQ which will connect to WebLogic - I'm not sure, perhaps this could work, I've never done it personally
* If you are thinking of setting up a WebSphere queue manager without installing WMQ binaries - to my knowledge this is impossible, the server part is proprietary and non-free, only the client part is proprietary and free. So this would rule out the idea above. But then again, please check it with IBM.

**Comment by drychlik76** [comment]
Honestly It's probably due to my ignorance with Websphere, web logic...  blah..  

The problem is, the provider cannot provide me with a queue manager name.  The thought that I had was, was setting up a local queue manager with a remote queue back to the provider.  Again, I'm not sure how this will work and I am ignorant when it comes to these technologies.  

Back to the drawing board.

**Comment by dsuch** [comment]
Yes, WebLogic and WebSphere are two distinct brands. There is also webMethods (not WebMethods) but this a different kettle of fish still.

If the endpoint that you are connecting to is WebSphere MQ then you absolutely need to know the name of the queue manager. If the person you are working with does not provide it then you need to escalate the issue because without it you don't have all connection parameters.

If the endpoint that you are connecting to is WebLogic then I'm afraid I don't know much about this suite of products - I met quite a few of them but they were used to host frontend applications instead of backend ones. So in this context it was them that connected to servers that I had under command rather than the other way around.

**Comment by dsuch** [comment]
Closing.
