### ISSUE TITLE
Request: PyMQI and Ansible

### ISSUE THREAD

**Issue by foafk** [dsuch/pymqi#49]
Ansible is based on Python. 
PyMQI is based on Python.
So , is there a "PyMQI" module  available for Ansible ?

**Comment by dsuch** [comment]
Hi @foafk,

there is no Ansible module for PyMQI that I am aware of.

Can you please explain how it would work? What sort of module are you thinking of? What kind of functionality are you looking for?

Regards.

**Comment by foafk** [comment]
I think we can combine ansible and pypqe to quiclly deploy new objects on MQ.
With Ansible, we can already fully automates the mq installations and patching.
I think it will great if we can also fully automates the new mq objects deployments.

**Comment by dsuch** [comment]
Hi @foafk - this is a good idea but I feel it is outside of this library's scope.

What I mean is that it sounds great and useful, but PyMQI is a lower-level library for connections themselves, and it would another library's work to plug it into Ansible.

I am hence closing the ticket but please do not think this is because I don't like this idea. I do, but it is simply not for PyMQI. If you would like to discuss it further - please contact me on dsuch@zato.io.

Regards.
