### ISSUE TITLE
Starting a stopped MQ

### ISSUE THREAD

**Issue by Ron4326** [dsuch/pymqi#53]
Hi,

Is it possible with pymqi module to start a remote Queue Manager if it is stopped ?
Something like 'strmqm'  command we run.

With pymqi, I can see if a qmgr is running or not with pymqi.connect(), it returns "2059: FAILED: MQRC_Q_MGR_NOT_AVAILABLE".

So, is it possible to start that qmgr ?

Thanks,
Ron

**Comment by dsuch** [comment]
Hello @Ron4326,

we can treat running strmqm as a specific case of a broader class of questions, i.e. is it possible to run commands on remote systems with PyMQI to which the answers is that this is not supported.

MQ APIs as such do not offer anything in this department so this is not that much of a limitation of PyMQI, it is simply outside of its scope because it only exposes to Python some of MQ APIs.

So to wrap it up, MQ APIs don't have such a feature and PyMQI does not let one to execute remote commands, strmqm including.

That all said, it is easy to do it in Python, e.g. here the paramiko library is used https://stackoverflow.com/a/3586168 and all of it is just a handful of lines of code.

Regards.

**Comment by Ron4326** [comment]
Thank you @dsuch. 
Yes, I guess I have to execute remote commands inorder to start the MQ. As I'm using IBM MQ in Windows, I think WMI module will do what I require, for running batch commands. Paramiko will be well suited for Linux box.
And sorry for the late reply, was involved in some other important work.

Regards,
Ron

**Comment by dsuch** [comment]
Hi @Ron4326 - I think the situation is resolved and I'm closing the ticket. If you need anything, please free to re-open to create a new one. Thanks!
