### ISSUE TITLE
PyMQI - speed & fine tuning

### ISSUE THREAD

**Issue by cristib89** [dsuch/pymqi#61]
Hi,

I had to write a tool which relies on PyMQI to manage messages on MQ7/8 queue managers (i.e copy, delete, search, etc).

I've reached a point where I can process on most servers about 1000 msgs/sec but I'm not sure what can be improved (the time to fulfill a task scales linearly) and I'm not sure if multithreading might help (considering that I'd like to maintain the order of the messages in the queue)

Any hints?

Thank you in advance

**Comment by dsuch** [comment]
Hello @cristib89,

1k req/s does not sound bad - is the limit of what this MQ queue manager can handle higher than that?

**Comment by cristib89** [comment]
I'll need to check... will come back with an update.

**Comment by dsuch** [comment]
Please do - you will also need to take into account if you are dealing with a single queue or multiple ones as well as message size and queue persistence options.

E.g. if you send messages big or not, and they need to be stored on disk, you will be likely limited by the queue manager's disk I/O.

In general, PyMQI itself is a thin wrapper around IBM's C libraries. They cannot be made any faster because MQ's license forbids alternative implementations. There is obviously some overhead yet you can assume performance near to C.

But you do need to fine-tune the queue manager and know what its limitations are, on your particular workload, and on this particular MQ environment.

**Comment by cristib89** [comment]
I will also test with connection in bindings mode to see if something is different.

Thanks a lot.

**Comment by cristib89** [comment]
yeah .... no difference between client vs bindings connection mode .... I guess I'll close the issue

thank you!

**Comment by lifeguard999** [comment]
I've come across similar issue when writing a batch which sent/received ~200k requests and noticed network traffic of just "sending" and "receiving" made an impact. So moving both "sending" and "receiving" to their own separate threads for network chatting (while local cpu-based message processing stayed on the main thread) improved things. 
I used python's Queue objects as message buffers (https://docs.python.org/2/library/queue.html), which made it rather simple in the end if you want to give it a shot. For message ordering you probably want to use correlation ID; otherwise the moment one of your messages gets dropped somewhere in the middle, the rest will be mismatched.

I would argue however this kind of optimisation lies outside of pymqi; it's going to depend on specific use case, namely whether threads are even needed, if so how how many etc.
