### ISSUE TITLE
Pure Python

### ISSUE THREAD

**Issue by lifeguard999** [dsuch/pymqi#64]
Is there a possibility to convert the module to pure Python, i.e. decommission the pymqe.c and instead load mq libraries dynamically at runtime? I think I've seen this done in the past and quick googling returns library such as 'ctypes' (built in from Python 2.6 up), which might just do that.
The huge benefit of this would be no need to compile the module when pip installing it. This is especially problematic on Windows + Python 3.5, where one needs VS 2015 to build, followed by Windows + Python 2.7 where one needs a (free but not there by default) 'MS VS for Python 2.7'. Even on Linux there are setups where gcc is not installed by default.
I don't think I've seen much going on in pymqe.c to justify it's existence, it seems to be just bining Python and MQ libs together, which if ctypes (or similar) can do at runtime directly from Python - problem solved.
The only thing coming to mind is possible performance impact, which would need to be checked, but on the face of it I doubt it'll be an issue (currently pymqe.so is after all dynamically linked and data transferred between Python and itself).

**Comment by dsuch** [comment]
Hello @lifeguard999 - using ctypes could be feasible as long as it was guaranteed to work on all the systems that are considered niche from the general perspective yet one can find them often in enterprise environments - AIX, HP-UX, Solaris and z/Linux.

The last one would be likely the least problematic, it would be probably always RHEL or SuSE. The first one would be most important. But the other two still do exist and are used.

It is because of these ramifications that I never attempted to rewrite it - I just consider PyMQI to be bound to be always several years behind everything because of such systems.

I learned to accept in a way that this is not the kind of project where one would use tools considered the best ones available otherwise, because there would be always some systems missing the infrastructure required.

Ideally, I would just implement the whole networking layer in Python and/or Cython but alas, MQ license forbids such attempts.

Please also note that pymqe.c implements the MQAI API too, i.e. administrative commands (define channel, create queue etc.), and it is not merely a thin wrapper as is the case with MQI.

**Comment by lifeguard999** [comment]
Understood. I won't be able to test on those exotic OSs. Nonetheless, let me go off and experiment if this is theoretically possible. Perhaps having an optional list of OSs where non-compiled version is confirmed to work is one option? On unsupported ones it could default to compiling as it does now.

**Comment by dsuch** [comment]
A related ticket #166 is about dropping support for certain platforms in order to facilitate a rewrite in Cython.

**Comment by dsuch** [comment]
Mass-closing old tickets.
