### ISSUE TITLE
Support for custom location of MQ libs

### ISSUE THREAD

**Issue by lifeguard999** [dsuch/pymqi#68]
Hello,
In setup.py there's a list of default paths where MQ's header and lib folders are expected to be. Now on some setups the install location is custom, so setup fails and one needs to manually edit the path in setup.py.
However what I noticed is upon installation MQ creates environment variables to find itself, among others a variable $MQ_FILE_PATH. Is that OK if I create a PR which (in case the default path does not exist) tries to use that $MQ_FILE_PATH to locate .h & .lib files?

**Comment by dsuch** [comment]
Thanks, yes, that sounds like a good idea.

**Comment by dsuch** [comment]
Thanks again @lifeguard999 - I think this ticket can be closed because during the works on ticket #89 a new way to discover such locations was added, namely, if you make the MQ binaries available on $PATH, this will suffice for the rest of the installation to be found.

Also, as hinted to in the same ticket by @JoshMcMQ, let's not use environment variables that start with MQ_* - they may be used by IBM at one point so in a case we ever need any such, let's make it start with PYMQI_*.
