### ISSUE TITLE
Multiple values in key-value pair attributes in PCFExecute, or multiple selectors to MQINQ

### ISSUE THREAD

**Issue by deliego** [dsuch/pymqi#83]
PCFExecute allows you to execute a command with arguments passed in a dictionary. Currently, you can pass a dictionary of key-value pairs, those keys are unique and values can only be "str" or "int". However, PCF itself allows you to pass a combination of attribute values, but you cannot in pymqi as it only accepts "str" or "int" in their values. For example:

```
import logging
import pymqi

queue_manager = "QM01"
channel = "SVRCONN.1"
host = "192.168.1.135"
port = "1434"
conn_info = "%s(%s)" % (host, port)

prefix = "SYSTEM.*"
queue_type = pymqi.CMQC.MQQT_LOCAL
queue_attrs = pymqi.CMQC.MQIA_OPEN_INPUT_COUNT

args = {pymqi.CMQC.MQCA_Q_NAME: prefix,
        pymqi.CMQC.MQIA_Q_TYPE: queue_type,
        pymqi.CMQCFC.MQIACF_Q_ATTRS: queue_attrs}

qmgr = pymqi.connect(queue_manager, channel, conn_info)
pcf = pymqi.PCFExecute(qmgr)

try:
    response = pcf.MQCMD_INQUIRE_Q(args)
except pymqi.MQMIError, e:
    if e.comp == pymqi.CMQC.MQCC_FAILED and e.reason == pymqi.CMQC.MQRC_UNKNOWN_OBJECT_NAME:
        logging.info("No queues matched given arguments.")
    else:
        raise
else:
    for queue_info in response:
        queue_name = queue_info[pymqi.CMQC.MQCA_Q_NAME]
        logging.info("Found queue [%s]" % queue_name)

qmgr.disconnect()

```
What I would like is to pass more than one value in queue_attrs, basically a list [pymqi.CMQC.MQIA_OPEN_INPUT_COUNT, pymqi.CMQC.MQIA_OPEN_OUTPUT_COUNT, pymqi.CMQC.MQIA_MAX_MSG_LENGTH]. The reason is because normally you request more than 1 attribute from a queue and getting "MQIACF_ALL" is too expensive (I don't need all 57 attributes) when you have hundreds or thousands of queues to inquire and only need 6-8 attributes.
The same thing happens with other commands like MQCMD_INQUIRE_CHANNEL_STATUS.

I tried using Queue.inquire instead but it only accepts 1 selector attribute and the command MQINQ can accept multiple selectors.

Is it possible to add that feature so that PCFExecute arguments accept a list of values as well and not just "str" or "int" in its dictionary? Also, enhance "inquire" so that it can receive multiple selectors?

Many thanks,

Diego

**Comment by dsuch** [comment]
Hello @deliego,

this does not sounds like a big extension but it is not a trivial one either - if you would like to sponsor its development please contact me using the address of dsuch@zato.io.

As of today, only string, integer and byte string values can be used, as you know. Under, MQAI calls are used to handle them with, respectively, mqAddString, mqAddInteger and mqAddByteString.

All of the MQAI API calls are listed below.

https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_7.5.0/com.ibm.mq.ref.adm.doc/q089140_.htm

**Comment by deliego** [comment]
Thanks @dsuch. Maybe I can do something to help on that once I get some time. I'll look at those MQAI calls as well.

**Comment by JoshMcMQ** [comment]
@dsuch and @deliego also not that IBM has stated in many locations that MQAI will not be enhanced and will likely be formally deprecated in a future release.  One of the major things it does not support is issuing PCF commands to z/OS mainframe queue managers.

If time is spent enhancing the the pymqi PCF functionality it would be good to convert it to use the standard PCF interface rather than the MQAI wrapper of the PCF interface.

Below are a few references I found when researching this about 2 years ago, related to z/OS support in MQAI, but it also shows in general IBM has stated it will not be enhanced going forward.

---

http://www-01.ibm.com/support/knowledgecenter/SSFKSJ_8.0.0/com.ibm.mq.adm.doc/q020070_.htm?lang=en

> The MQAI is an administration interface to IBM® MQ that is available on the AIX®, HP-UX, IBM i, Linux, Solaris, and Windows platforms.  **<<< Note the lack of z/OS as a platform.**

---

https://www.ibm.com/developerworks/rfe/execute?use_case=viewRfe&CR_ID=61808

> There are no plans to make any enhancements to the MQAI library; there are very few users of it, and it is likely to be formally deprecated in a future release of MQ.
> 
> Therefore this request is being rejected.
> Posted by IBM_Development (IBM) on 10 Nov 2014

---

Another good presentation from one of the IBM Hursley developers about PCF in general and it also has a similar comment about MQAI and z/OS:
http://mqtechconference.com/sessions_v2015/MQ_PCF.pdf

> There is also MQAI originally intended to simplify programs but it too does not contain all function
> – Has concept of "bags" – put in elements, pull out elements
> – In particular, extensions to support z/OS formats are missing
> – And is not available on z/OS

I think Page 13 of the MQ_PCF.pdf really goes into why z/OS is not supported today:

> * z/OS started to support real PCF for commands from V6
> * But command server requires extended-format PCF messages
> 
> How is z/OS different Other platforms | z/OS
> -- | --
> MQCFH in requests has type   MQCFT_COMMAND | MQCFH in requests has type   MQCFT_COMMAND_XR
> Single type of response message   (MQCFT_RESPONSE) | Up to three types of response   message (MQCFT_XR_MSG, MQCFT_XR_ITEM, MQCFT_XR_SUMMARY)
> MQCFH Control field indicates last   response | MQCFH Control field indicates last   response in group
> Single logical collection of   responses | Responses may be grouped into multiple   logical groups (grouping information embedded in response parameters)

**Comment by SeyfSV** [comment]
Fixed in 561751289289906166193a3bd6b02cf515da0496

**Comment by deliego-github** [comment]
Thanks @SeyfSV. I am not sure if it was fixed just in attributes but I noticed the same behaviour in the way it connects as well.:

qmgr.connect_with_options(queueManager, cd, sco, opts=connect_options)

opts only accepts 1 value, basically, 1 option when it should probably accept more than one. For example, I want to pass MQCNO_HANDLE_SHARE_BLOCK and MQCNO_RECONNECT but it only accepts 1 value, instead of a list.

I just wanted to mention it while it is still fresh :)

**Comment by chughts** [comment]
The options for opts should be `or`ed together. So in your case:

```python
connect_options = pymqi.CMQC..MQCNO_HANDLE_SHARE_BLOCK | pymqi.CMQC..MQCNO_RECONNECT
```

Although as they are a binary pattern then adding them should also work.

```python
connect_options = pymqi.CMQC..MQCNO_HANDLE_SHARE_BLOCK + pymqi.CMQC..MQCNO_RECONNECT
```

**Comment by mrkksparrow** [comment]
I am getting authorization error for the line 

pcf = pymqi.PCFExecute(qmgr)

The error msg is 

File "/usr/local/lib/python3.8/dist-packages/pymqi/__init__.py", line 1828, in __realOpen
    raise MQMIError(rv[-2], rv[-1])
pymqi.MQMIError: MQI Error. Comp: 2, Reason 2035: FAILED: MQRC_NOT_AUTHORIZED

What Authority must be given to clear this error, or shoul i configure anything on the IBM MQ queue manager properties?

**Comment by dsuch** [comment]
Hello @mrkksparrow,

this is not a general IBM MQ support forum. The fact that you use PyMQI does not absolve you from the need to learn how IBM MQ works before you can connect to it using Python.

Also, if you need any kind of assistance from people here who do it in their spare time, learn more about how to open tickets in open-source support projects. Do not post half-working code without any context and details.
