### ISSUE TITLE
Local units of work are committed if python interpreter crashes

### ISSUE THREAD

**Issue by frymer** [dsuch/pymqi#84]
When using a syncpoint to consume messages from a queue a local unit of work is created, allowing the client application to commit or backout (rollback) the messages consumed within that local unit of work. This is useful to try and guarantee that messages aren't lost if something went wrong in the client while processing them. However while using pymqi I noticed that if the program ends abruptly by an exception or even if it ends normally without explicitly committing or backing the unit of work out the unit of work is committed and messages are potentially lost.
The IBM official documentation explains:

> Units of work that involve only the queue manager are called local units of work. Syncpoint coordination is provided by the queue manager itself (internal coordination) using a single-phase commit process.
> 
> To start a local unit of work, the application issues MQGET, MQPUT, or MQPUT1 requests specifying the appropriate syncpoint option. The unit of work is committed using MQCMIT or rolled back using MQBACK. However, the unit of work also ends when the connection between the application and the queue manager is broken, intentionally or unintentionally.
> 
> If an application disconnects (MQDISC) from a queue manager while a global unit of work coordinated by IBM® MQ is still active, an attempt is made to commit the unit of work. If, however, the application terminates without disconnecting, the unit of work is rolled back as the application is deemed to have terminated abnormally.

Inquiring this further using wireshark I noticed pymqi always send MQDISC to the server, and by that committing the unit of work.
Reviewing the code I found it to be caused by the attempt to close the queue manager inside the 
__ del __ magic method, which is called as a destructor whenever and for whatever reason the python interpreter exits.

I tried forking the project and removing the disconnect call from the __ del __ method and it seems to solve the problem.

What are the considerations for calling the qmgr's disconnect method within the __ del __ method?
Are there any risks in removing it? If so, are there risks in adding a call to the backout method prior to that?

If this seems like a legitimate issue I am happy to create a pull request for my changes and get instructions on how to further test this change to make sure other functionalities aren't affected.

Thanks in advance!

**Comment by dsuch** [comment]
Hi @frymer,

the only caveat that I can think of is that the current behaviour has been around for 15+ years and all the existing PyMQI-based applications rely on it, even if implicitly.

I recognize your use case, though, so if you could just add a 'disconnect_on_exit' parameter to QueueManager's ```__init__``` that ```__del__``` would be taking into account, I think that would deal with it nicely.

This parameter would default to False to keep the current behaviour but one could provide True to support the needs such as yours.

What do you think?

**Comment by dsuch** [comment]
I merged PR #85 - thank you @frymer.

**Comment by colinpaicemq** [comment]
I used to work in MQ development at IBM.   I think this is an application coding problem.
You should always put in a commit or backout in your code ( unless you are only using out of sycnpoint messages when it does not matter).  If the code was able to send an MQDISC, then your application should have had an opportunity to clean up.   This is especially needed when you are doing MQ and database and 2 phase commit.

**Comment by JoshMcMQ** [comment]
@colinpaicemq  note that I explained this behavior in #76, basically in distributed platforms if `MQDISC` is called when there is an outstanding unit of work it will be committed, the page I linked to in the IBM KC does explain that the behavior is different on z/OS.  On #76 @michaeljulio2107 pointed when a "exit" was called without commit the message was still committed.  I asked @michaeljulio2107 to try killing the process with a `kill -KILL` and this did get backed out as I expected.

I think with the change @frymer provided in this issue @michaeljulio2107's "exit" test will back out if the disconnect_on_exit parameter was set.

Note that I had @michaeljulio2107 test with `kill -KILL` (note that `-KILL` is same as `-9`) so that python would not be able to catch it and do any cleanup.  Now I know that the cleanup that was being performed is via the QueueManager's `__del__` and it makes sense.

Colin, do you think anything needs to change?  As of now the legacy behavior of pymqi calling `MQDISC` when it cleans up is maintained by default and to turn this off a new parameter `disconnect_on_exit` was added.  This seems very reasonable to me.

**Comment by colinpaicemq** [comment]
I think leave the fix in.  People do not have to use it (grin).
I remember a customer having a similar problem - where the application did not do a commit (and it sat around doing nothing for a few hours).   They could not change the application because they had lost the source of the program.
