### ISSUE TITLE
Dead letter queue support

### ISSUE THREAD

**Issue by deliego** [dsuch/pymqi#88]
Hi again :)

I saw that there was an old post about adding Dead Letter Handler support here:
https://answers.launchpad.net/pymqi/+question/176164

I basically am looking for that, a way to read the reason, destination of a message in the dead letter queue. Did that make it into pymqi? According to the post, it was going to.

Any alternative on getting that? If I am able to get the MQDLH structure, I could get those fields.

Thanks,

Diego

**Comment by dsuch** [comment]
Hi @deliego,

it was not incorporated but I do not remember the reason for it - I do not have access to the email with the patch with correct formatting.

I think this Launchpad thread could be a good starting point - do you think you could work on a PR based on it?

The only thing is that it was taking place seven years ago and now we have Python 3 support so that also would have to be taken into account.

Thanks.

**Comment by deliego** [comment]
Thanks @dsuch. I'm going to play with it. The code is there, just needs reformatting and rebuilding. :)
