### ISSUE TITLE
GroupId doesn't set

### ISSUE THREAD

**Issue by semakmillev** [dsuch/pymqi#91]
Hi!
I have the same problem as mentioned here:
https://python-forum.io/Thread-pymqi-and-group-id-MQ
While sending message, i cannot set GroupId (it always consists of zeroes). Am i doing something wrong?
```python
from pymqi.CMQC import MQFMT_STRING, MQMF_MSG_IN_GROUP
import pymqi
qmgr = pymqi.connect('TEST', 'SVRCONN', '0.0.0.0(1423)','usr','')
queue_name= "TEST.Q"
q = pymqi.Queue(qmgr, queue_name)
mqmd = pymqi.MD()
mqmd['GroupId'] = b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00'
mqmd['Format'] =  MQFMT_STRING
mqmd['MsgFlags'] = pymqi.CMQC.MQMF_MSG_IN_GROUP
msg = '<test/>'
q.put(msg.encode('utf-8'), mqmd)
request_md = pymqi.MD()
q.close()
q = pymqi.Queue(qmgr, queue_name)
msg = q.get(None, request_md) #, gmo)
print(request_md)
q.close()
qmgr.disconnect()
```
In this example request_md['GroupId'] full of zeroes. Of course, if somebody reads message by something else he will get zeroes too.

**Comment by dsuch** [comment]
You need to specify MQMD Version 2 in both put and get options for GroupId to be taken into account, otherwise it is ignored.

md.Version = pymqi.CMQC.MQMD_VERSION_2

There are other hints and tips here too:

https://www.ibm.com/support/knowledgecenter/SSFKSJ_9.0.0/com.ibm.mq.ref.dev.doc/q097530_.htm

**Comment by dsuch** [comment]
Closing due to user inactivity.
