### ISSUE TITLE
z/OS support

### ISSUE THREAD

**Issue by deliego** [dsuch/pymqi#92]
Hi there,

Currently it says that pymqi supports z/OS but not exactly sure which versions. I read that pymqi uses MQAI and MQAI is not available to z/OS 8.0 and I couldn't find anywhere if MQAI is available to MQ 9.0 on z/OS.

My question is, how does pymqi currently support z/OS? Does it issue script commands (MQSC) instead?

Thanks!

**Comment by dsuch** [comment]
Hi @deliego,

PCF commands such as creation of queues or getting a list of commands will not work currently when used with a z/OS queue manager because under the hood MQAI is used to implement such commands and MQAI does not support z/OS.

PyMQI does not issue any other scripts instead - I do not have access to any LPAR to test it but there will be likely some low-level MQ error indicating that fact.

What works with z/OS are MQI verbs, e.g. GET or PUT.

I desire to have support for PCF and z/OS but this definitely needs a sponsor because it requires a rather substantial rewrite of how PCF are sent and received.

Such a sponsor would also need to grant access to a development LPAR to test it with.

Again, if anyone is interested in it, please always feel free to contact me on dsuch at zato.io.

**Comment by deliego** [comment]
Thanks @dsuch! I have taken down your information. I'll let you know if we get a demand for it and will contact you again.

**Comment by siuside** [comment]
@dsuch Why would it require a rewrite? Can you please give a high level idea of how to go about this?

**Comment by dsuch** [comment]
Hello @siuside - this would require a rewrite because z/OS does not support MQAI which is the underlying protocol that PyMQI's support for PCF is based on.

This was implemented around 15 years ago by a different person, in times when very few people had an inkling that Python would become a widely popular language and getting access to z/OS was even harder than today, so the person did as much as was possible at that time.

A high-level idea is to remove MQAI completely and replace it with something that works on all systems. However, this means replacing a large part of PyMQI that has been super-stable for 15 years and it is something that I would prefer to do myself.

But for me to spend a couple hundred hours on such a rewrite means that a sponsor is needed. If you would like to discuss it, please contact me on dsuch@zato.io. Thank you.

**Comment by jjjw420** [comment]
Please have a look at:
https://github.com/jjjw420/pymqi/blob/master/code/pymqi/mq_pcf.py

It implements the PCF headers and some helper classes which are not currently present in pymqi.   It facilitates the packing, unpacking, sending and receiving of IBM MQ PCF messages to queue managers on multiple platforms (tested on Z/OS, Linux, AIX, Windows).

I wrote the bulk of this back in 2016 specifically as I was required to send MQSC and PCF commands to a Z/OS queue manager.   The intention was to merge it back into pymqi at some stage but some of it requires some discussion(eg. suitability, useability, etc.).  This is a work in progress and the python2 to python3 conversion was done rather hastely just before posting this.

Like @siuside i realised quickly that PCFExecute does not work on Z/OS.  I investigated the problem with PCFExecute and Z/OS briefly but due to where it is in pymqi I went for constructing and sending my own PCF messages instead.

In order process PCF messages on Z/OS it was required that the PCF headers contain  big-endian numerics.  So I required an MQOpts class that allowed for the numeric encoding to be set(similar to the RFH2 header processing I wrote before).   Packing and unpacking PCF "bags" also required some helper classes to facilitate the creation and parsing of PCF messages.  

This is how it typically how it can be used to Z/OS queue manager(enquire queue depths on SYSTEM.DEFAULT.*):

`
pcf_c = PCFCommand(qmgr, zos=True)

pcf_r = pcf_c.execute_command(pymqi.CMQCFC.MQCMD_INQUIRE_Q, [(pymqi.CMQC.MQCA_Q_NAME, b"SYSTEM.DEFAULT.*"), (pymqi.CMQC.MQIA_Q_TYPE, pymqi.CMQC.MQQT_LOCAL), (pymqi.CMQCFC.MQIACF_Q_ATTRS, [pymqi.CMQC.MQCA_Q_NAME,pymqi.CMQC.MQIA_Q_TYPE,pymqi.CMQC.MQIA_MAX_Q_DEPTH])])

print("Comp code:", pcf_r.comp_code, " Reason code:", pcf_r.reason_code)
for q in pcf_r.parms:
   print("Q Name:", q[pymqi.CMQC.MQCA_Q_NAME], "Q depth:", q[pymqi.CMQC.MQIA_CURRENT_Q_DEPTH])
`

or to send a MQSC command:
`
pcf_c = PCFCommand(qmgr, zos=True)
print(pcf_c.mqsc_command("DIS QL(SYSTEM.DEFAULT.*) ALL"))
`

If the consensus is that this does have a home in pymqi - I will gladly do the work to get it in.

Please advise what you think.

@jjjw420

**Comment by JoshMcMQ** [comment]
Another similar request: https://github.com/dsuch/pymqi/issues/83

@dsuch is this something that can be included?

**Comment by dsuch** [comment]
@JoshMcMQ I would be happy to add support for z/OS but I do not have access to any development LPAR and it would be difficult for me to support such an addition.

If anyone can grant such an access then it would be much better in the longer run.

That said, @jjjw420 is a long-time PyMQI contributor and I will be checking out his code later this month when I have an opportunity to work on MQ in work projects.

But truly, it boils down to a great degree to the lack of access to an MQ LPAR for PyMQI development purposes.

**Comment by JoshMcMQ** [comment]
@chughts @oljarast is access to a z/OS LPAR something IBM can provide for the maintainer of pymqi?  Something like [IBM Z Remote Development Program](http://dtsc.dfw.ibm.com/MVSDS/'HTTPD2.ENROL.PUBLIC.SHTML(ZOSRDP)') with MQ installed that does not have a cost associated?

**Comment by chughts** [comment]
@dsuch The MQ Beta programme offers access to MQ z/OS queue managers albeit on a 'best efforts' basis. We will contact you to see if this is an option for you.

**Comment by jjjw420** [comment]
Bear in mind though that the code I wrote mentioned above covers PCF in general - it's not specific to Z/OS at all.   It provides the PCF headers so that you can create, parse, send and receive the MQ PCF command messages yourself if need be - on any platform.  The packing and unpacking of the PCF "bags" sucks a bit - hence the helper classes and methods to help facilitate that.

So this is technically not really "Z/OS" support for pymqi -  it's PCF support that will work on any platform that can do PCF(all of them tese days I think).   It does not fix the issues with PCFExecute.  It merely provides a "raw" MQ mechamism to send and receive PCF command messages.   

So - if we decide to include this in the library - it should rather be included as "PCF" support - that can be used on multiple platforms.

I do not mind making it work and doing the work(cleanup, names, tests, documentation) so that it can be included in this great library(even if only for completeness)!   

I have access to Z/OS queue managers in both my professional and personal capacity.   I will talk to some of the guys to see if I can get some of the contributers of pymqi access to these "test" Z/OS queue managers.

* I pledge - here and now - to be more involved with pymqi going forward.   So I truly do not mind taking this onto myself. *

Let me know.   Give it some thought.

PS.  With regards to fixing PCFexecute for Z/OS.  It is possible - but is it worth it? Especially if we decide to include PCF.   I will run some tests and dumps over the coming days to indicate the problem with PCFexecute on Z - and then the contributers should decide on suitability and effort.  But I remember that something about the fix was far reaching and a little painfull.

**Comment by dsuch** [comment]
Hi Johannes,

it is good to hear that you have more time but please do not feel compelled to anything. We are all adults here and in a project like this it is natural to witness both tides and ebbs.

I do not feel that salvaging PCFExecute for z/OS makes much sense. I would also wager that most people do not really care if they have PCF or not as long as they can manage their MQ objects in one way or another using a convenient Python API.

That said, PCFExecute has been around for almost 20 years so we cannot remove it. Anything added instead of it would have to keep backward compatibility.

This also makes everything easier as far as maintenance goes - we can just point people to relevant pieces of MQ PCF documentation.

This simplifies usage too by keeping PyMQI more or less API-compatible with C and Java without requiring users to re-learn everything simply because PyMQI is in Python.

On the other hand, internally rewriting PCF somehow is required sooner or later because the current underlying implementation uses MQAI which is something that IBM says will be removed from the product one day.

I have not looked at your code yet, I will do it as soon as I can. Thanks.

**Comment by jjjw420** [comment]
I'm with you.    PCFExecute should stay the way it is.  100%.     I'm certainly not suggesting it should be changed.   

Frankly - when this was written I was not even comfortable with it being in the main pymqi module - hence the completely separate script even.  

It's such a specialised requirement is PCF.   Lower level IBM MQ administration and knowledge that the majortity of MQ users will never need.   But I suppose it did stem from wanting to be able to send MQSC and admin messages to any queue manager on any platform.  

It was brought to this forum as it's an example of how pymqi can be used for Z/OS and multi-platform admin by using PCF command messages.   So technically pymqi does support Z/OS - it just requires a little more legwork.

**Comment by jjjw420** [comment]
Have you decided on the structure of this enhancement?  as before - a few hings have always bothered me about this?  Does this belong in the main pymqi module considering the almost *painfull* subclass of MQOpts to cater for numeric encodings?

**Comment by dsuch** [comment]
Hello @jjjw420 - I am sorry but I am completely tied up elsewhere and I will not be able to look at it in the foreseeable future, at least in the next weeks or likely for longer.

If you are only asking if ```pymyqi/__init__.py``` is a good place then likely it is not - that module is already quite big so introducing something like ```pymqi/zos.py```, with code that ```pymqi/__init__``` imported, would sound much better.

**Comment by jjjw420** [comment]
No problem.   I know how things are.  

It's pretty standalone.  It's more about raw MQ PCF messages and comms on multiplatform than ZOS.    It supports Z/OS because you can set the numeric encoding depending on platform.

Have a look when you have a moment.

**Comment by SeyfSV** [comment]
Hi,
@jjjw420 Please take a look on branch d89ee8b. Is it solves your wishes?

For all:
What was done:
* Moved from MQAI to raw PCF
* Added new way for setting PCF message content and filter
* Added parsing of arbitrary PCF message
* Now MQOpts can has `list` as parameter value

Questions:
* I can't find info about using multiple filters. If some one know about this, please write.
* PCFExecute now has unpack function. It unpacks PCF message to dictionary. Maybe it is not convinient. If so, report.

@dsuch , I added type hints to all parts of code, that I altered. Is it ok?

**Comment by jjjw420** [comment]
Busy checking it out.
will let you know.

**Comment by JoshMcMQ** [comment]
I would suggest by default add options `MQRO_DISCARD_MSG` and
`MQRO_PASS_DISCARD_AND_EXPIRY` to `MQMD.Report` before the command
message is put to the command server's input queue.  This prevents unneeded DLQ messages for both the initial request and for the command server replies.

**Comment by JoshMcMQ** [comment]
See my comments here for a better description:

https://github.com/fbraem/mqweb/issues/18

**Comment by salapat11** [comment]
Hi @SeyfSV , 

Thanks for the raw PCF code.  Can you please review https://github.com/dsuch/pymqi/pull/198?  This PR adds support to z/OS queue managers.
